# We need to make sure the checked-in `index.js` actually matches what we expect it to be.
name: Check Binary

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  check-bin:
    name: Check Dist has been Updated
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Node
        id: node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile --prefer-offline
        shell: bash

      - name: Rebuild the index.js file
        run: yarn build
        shell: bash

      - name: Compare the expected and actual dist/ directories
        id: diff
        run: |
          if [ "$(git diff --ignore-space-at-eol bin/ | wc -l)" -gt "0" ]; then
            echo "Detected uncommitted changes after build.  See attached artifacts and status below:"
            git diff
            exit 1
          fi
        shell: bash

      # If bin/ was different from expected, upload the expected version as an artifact
      - uses: actions/upload-artifact@v2
        if: ${{ failure() && steps.diff.conclusion == 'failure' }}
        with:
          name: bin
          path: bin/